import { AIProviderConfig } from "./ai-provider.types";

export const DEFAULT_AI_PROVIDERS: AIProviderConfig[] = [
  {
    provider: "auto",
    model: "auto-router-v1",
    enabled: false,
    displayName: "算力自动调度 (Auto-routing)",
    status: "not_configured",
    description: "系统根据诊断复杂程度，自动分流决策模型和轻量分析模型，优化响应时延与决策精度。",
    safetyNotice: "自动调度遵守核心安全框架，仅将诊断数据发送给合规的服务提供商，禁止任何自主修改账户操作。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: true,
    supportsReviewTemplate: true,
  },
  {
    provider: "gemini",
    model: "gemini-2.5-flash",
    enabled: false,
    displayName: "Google Gemini",
    status: "not_configured",
    description: "高效的推理多模态引擎，擅长长文本分析及复杂漏斗模型对账与数据血缘关系分析。",
    safetyNotice: "遵守数据隐私安全协定。所有广告出资与像素配置策略推荐纯属辅助意见，必须人工审查后实施。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: true,
    supportsReviewTemplate: true,
  },
  {
    provider: "openai",
    model: "gpt-4o",
    enabled: false,
    displayName: "OpenAI ChatGPT",
    status: "not_configured",
    description: "行业标杆级通用语言模型，具备极高的代码理解与策略解构稳定性，辅助生成行动路线图。",
    safetyNotice: "坚守人工验证底线。推荐的操作建议需要经由拥有相应权限的用户在平台控制台上手工执行。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: true,
    supportsReviewTemplate: true,
  },
  {
    provider: "claude",
    model: "claude-3-5-sonnet",
    enabled: false,
    displayName: "Anthropic Claude",
    status: "not_configured",
    description: "拥有卓越代码设计与数理分析能力的模型，能提供极高质量的店铺归因原因分析与像素校验脚本推荐。",
    safetyNotice: "模型没有任何执行层集成。禁止自动写入 Meta Graph API 凭证，一切建议仅作展示用途。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: true,
    supportsReviewTemplate: true,
  },
  {
    provider: "deepseek",
    model: "deepseek-chat",
    enabled: false,
    displayName: "DeepSeek",
    status: "not_configured",
    description: "极具性价比中文亲和力强的推理模型，擅长总结运营情况与提炼复杂大盘摘要，结构化输出优秀。",
    safetyNotice: "在安全沙箱中分析静态指标，绝不对实际线上广告项目进行静默电销出价或停止投放。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: true,
    supportsReviewTemplate: true,
  },
  {
    provider: "qwen",
    model: "qwen-max",
    enabled: false,
    displayName: "阿里云通义千问 (Qwen)",
    status: "not_configured",
    description: "专为亚太电商生态进行微调和深度演进的模型，能完美理解复杂的中文财务报表与对账指标定义。",
    safetyNotice: "严防数据泄漏，所有传输数据脱敏处理。系统严禁未获得人工二次授权的各种高风险执行流。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: true,
    supportsReviewTemplate: true,
  },
  {
    provider: "local",
    model: "llama-3-8b",
    enabled: false,
    displayName: "边缘轻量化本地模型 (Local)",
    status: "not_configured",
    description: "部署在隔离局域服务器的小型语言模型，物理隔离运行，处理基础数据诊断、剔除外部传输安全顾虑。",
    safetyNotice: "纯本地运行，不将任何敏感账面开销、授权 Token 往返传输。所有控制权均绝对保留在本地客户端。",
    supportsIssueExplanation: true,
    supportsDashboardSummary: false,
    supportsReviewTemplate: false,
  }
];
